/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated/_shell'
import { Route as AuthenticatedIncidentComposeRouteImport } from './routes/_authenticated/incident-compose'
import { Route as AuthenticatedShellIndexRouteImport } from './routes/_authenticated/_shell/index'
import { Route as AuthenticatedShellAgentsRouteImport } from './routes/_authenticated/_shell/agents'
import { Route as AuthenticatedShellDirectoryRouteImport } from './routes/_authenticated/_shell/directory'
import { Route as AuthenticatedShellReportsRouteImport } from './routes/_authenticated/_shell/reports'
import { Route as AuthenticatedShellDirectoryIndexRouteImport } from './routes/_authenticated/_shell/directory/index'
import { Route as AuthenticatedShellDirectoryCustomerIdRouteImport } from './routes/_authenticated/_shell/directory/$customerId'
import { Route as AuthenticatedShellDirectoryCustomerIdIndexRouteImport } from './routes/_authenticated/_shell/directory/$customerId/index'
import { Route as AuthenticatedShellDirectoryCustomerIdPropertyIdRouteImport } from './routes/_authenticated/_shell/directory/$customerId/$propertyId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentComposeRoute =
  AuthenticatedIncidentComposeRouteImport.update({
    id: '/incident-compose',
    path: '/incident-compose',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShellIndexRoute = AuthenticatedShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedShellRoute,
} as any)
const AuthenticatedShellAgentsRoute =
  AuthenticatedShellAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDirectoryRoute =
  AuthenticatedShellDirectoryRouteImport.update({
    id: '/directory',
    path: '/directory',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellReportsRoute =
  AuthenticatedShellReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDirectoryIndexRoute =
  AuthenticatedShellDirectoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShellDirectoryRoute,
  } as any)
const AuthenticatedShellDirectoryCustomerIdRoute =
  AuthenticatedShellDirectoryCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AuthenticatedShellDirectoryRoute,
  } as any)
const AuthenticatedShellDirectoryCustomerIdIndexRoute =
  AuthenticatedShellDirectoryCustomerIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShellDirectoryCustomerIdRoute,
  } as any)
const AuthenticatedShellDirectoryCustomerIdPropertyIdRoute =
  AuthenticatedShellDirectoryCustomerIdPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => AuthenticatedShellDirectoryCustomerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedShellIndexRoute
  '/login': typeof LoginRoute
  '/incident-compose': typeof AuthenticatedIncidentComposeRoute
  '/agents': typeof AuthenticatedShellAgentsRoute
  '/directory': typeof AuthenticatedShellDirectoryRouteWithChildren
  '/reports': typeof AuthenticatedShellReportsRoute
  '/directory/$customerId': typeof AuthenticatedShellDirectoryCustomerIdRouteWithChildren
  '/directory/': typeof AuthenticatedShellDirectoryIndexRoute
  '/directory/$customerId/$propertyId': typeof AuthenticatedShellDirectoryCustomerIdPropertyIdRoute
  '/directory/$customerId/': typeof AuthenticatedShellDirectoryCustomerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedShellIndexRoute
  '/login': typeof LoginRoute
  '/incident-compose': typeof AuthenticatedIncidentComposeRoute
  '/agents': typeof AuthenticatedShellAgentsRoute
  '/reports': typeof AuthenticatedShellReportsRoute
  '/directory': typeof AuthenticatedShellDirectoryIndexRoute
  '/directory/$customerId/$propertyId': typeof AuthenticatedShellDirectoryCustomerIdPropertyIdRoute
  '/directory/$customerId': typeof AuthenticatedShellDirectoryCustomerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/incident-compose': typeof AuthenticatedIncidentComposeRoute
  '/_authenticated/_shell/agents': typeof AuthenticatedShellAgentsRoute
  '/_authenticated/_shell/directory': typeof AuthenticatedShellDirectoryRouteWithChildren
  '/_authenticated/_shell/reports': typeof AuthenticatedShellReportsRoute
  '/_authenticated/_shell/': typeof AuthenticatedShellIndexRoute
  '/_authenticated/_shell/directory/$customerId': typeof AuthenticatedShellDirectoryCustomerIdRouteWithChildren
  '/_authenticated/_shell/directory/': typeof AuthenticatedShellDirectoryIndexRoute
  '/_authenticated/_shell/directory/$customerId/$propertyId': typeof AuthenticatedShellDirectoryCustomerIdPropertyIdRoute
  '/_authenticated/_shell/directory/$customerId/': typeof AuthenticatedShellDirectoryCustomerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/incident-compose'
    | '/agents'
    | '/directory'
    | '/reports'
    | '/directory/$customerId'
    | '/directory/'
    | '/directory/$customerId/$propertyId'
    | '/directory/$customerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/incident-compose'
    | '/agents'
    | '/reports'
    | '/directory'
    | '/directory/$customerId/$propertyId'
    | '/directory/$customerId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/_shell'
    | '/_authenticated/incident-compose'
    | '/_authenticated/_shell/agents'
    | '/_authenticated/_shell/directory'
    | '/_authenticated/_shell/reports'
    | '/_authenticated/_shell/'
    | '/_authenticated/_shell/directory/$customerId'
    | '/_authenticated/_shell/directory/'
    | '/_authenticated/_shell/directory/$customerId/$propertyId'
    | '/_authenticated/_shell/directory/$customerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incident-compose': {
      id: '/_authenticated/incident-compose'
      path: '/incident-compose'
      fullPath: '/incident-compose'
      preLoaderRoute: typeof AuthenticatedIncidentComposeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell/': {
      id: '/_authenticated/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellIndexRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/agents': {
      id: '/_authenticated/_shell/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedShellAgentsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/directory': {
      id: '/_authenticated/_shell/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedShellDirectoryRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/reports': {
      id: '/_authenticated/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedShellReportsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/directory/': {
      id: '/_authenticated/_shell/directory/'
      path: '/'
      fullPath: '/directory/'
      preLoaderRoute: typeof AuthenticatedShellDirectoryIndexRouteImport
      parentRoute: typeof AuthenticatedShellDirectoryRoute
    }
    '/_authenticated/_shell/directory/$customerId': {
      id: '/_authenticated/_shell/directory/$customerId'
      path: '/$customerId'
      fullPath: '/directory/$customerId'
      preLoaderRoute: typeof AuthenticatedShellDirectoryCustomerIdRouteImport
      parentRoute: typeof AuthenticatedShellDirectoryRoute
    }
    '/_authenticated/_shell/directory/$customerId/': {
      id: '/_authenticated/_shell/directory/$customerId/'
      path: '/'
      fullPath: '/directory/$customerId/'
      preLoaderRoute: typeof AuthenticatedShellDirectoryCustomerIdIndexRouteImport
      parentRoute: typeof AuthenticatedShellDirectoryCustomerIdRoute
    }
    '/_authenticated/_shell/directory/$customerId/$propertyId': {
      id: '/_authenticated/_shell/directory/$customerId/$propertyId'
      path: '/$propertyId'
      fullPath: '/directory/$customerId/$propertyId'
      preLoaderRoute: typeof AuthenticatedShellDirectoryCustomerIdPropertyIdRouteImport
      parentRoute: typeof AuthenticatedShellDirectoryCustomerIdRoute
    }
  }
}

interface AuthenticatedShellDirectoryCustomerIdRouteChildren {
  AuthenticatedShellDirectoryCustomerIdPropertyIdRoute: typeof AuthenticatedShellDirectoryCustomerIdPropertyIdRoute
  AuthenticatedShellDirectoryCustomerIdIndexRoute: typeof AuthenticatedShellDirectoryCustomerIdIndexRoute
}

const AuthenticatedShellDirectoryCustomerIdRouteChildren: AuthenticatedShellDirectoryCustomerIdRouteChildren =
  {
    AuthenticatedShellDirectoryCustomerIdPropertyIdRoute:
      AuthenticatedShellDirectoryCustomerIdPropertyIdRoute,
    AuthenticatedShellDirectoryCustomerIdIndexRoute:
      AuthenticatedShellDirectoryCustomerIdIndexRoute,
  }

const AuthenticatedShellDirectoryCustomerIdRouteWithChildren =
  AuthenticatedShellDirectoryCustomerIdRoute._addFileChildren(
    AuthenticatedShellDirectoryCustomerIdRouteChildren,
  )

interface AuthenticatedShellDirectoryRouteChildren {
  AuthenticatedShellDirectoryCustomerIdRoute: typeof AuthenticatedShellDirectoryCustomerIdRouteWithChildren
  AuthenticatedShellDirectoryIndexRoute: typeof AuthenticatedShellDirectoryIndexRoute
}

const AuthenticatedShellDirectoryRouteChildren: AuthenticatedShellDirectoryRouteChildren =
  {
    AuthenticatedShellDirectoryCustomerIdRoute:
      AuthenticatedShellDirectoryCustomerIdRouteWithChildren,
    AuthenticatedShellDirectoryIndexRoute:
      AuthenticatedShellDirectoryIndexRoute,
  }

const AuthenticatedShellDirectoryRouteWithChildren =
  AuthenticatedShellDirectoryRoute._addFileChildren(
    AuthenticatedShellDirectoryRouteChildren,
  )

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellAgentsRoute: typeof AuthenticatedShellAgentsRoute
  AuthenticatedShellDirectoryRoute: typeof AuthenticatedShellDirectoryRouteWithChildren
  AuthenticatedShellReportsRoute: typeof AuthenticatedShellReportsRoute
  AuthenticatedShellIndexRoute: typeof AuthenticatedShellIndexRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellAgentsRoute: AuthenticatedShellAgentsRoute,
  AuthenticatedShellDirectoryRoute:
    AuthenticatedShellDirectoryRouteWithChildren,
  AuthenticatedShellReportsRoute: AuthenticatedShellReportsRoute,
  AuthenticatedShellIndexRoute: AuthenticatedShellIndexRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
  AuthenticatedIncidentComposeRoute: typeof AuthenticatedIncidentComposeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
  AuthenticatedIncidentComposeRoute: AuthenticatedIncidentComposeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
